# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-28 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=1, editable=False)),
                ('title', models.CharField(max_length=1000)),
                ('url', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=1, editable=False)),
                ('title', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialMediaProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=1, editable=False)),
                ('title', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=1000)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
