# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bona_fides", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="award",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="skill",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="socialmediaprofile",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
