# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bona_fides", "0002_auto_20170529_2228"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clip",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("url", models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
