# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bona_fides", "0003_clip"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clip",
            options={"ordering": ("-date",)},
        ),
        migrations.AddField(
            model_name="clip",
            name="date",
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
