# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bona_fides', '0004_auto_20170529_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='type',
            field=models.CharField(choices=[(b'app', b'App'), (b'story', b'Story'), (b'software', b'Software')], default='', max_length=100),
            preserve_default=False,
        ),
    ]
