# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-08 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bona_fides', '0005_clip_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='type',
            field=models.CharField(choices=[(b'app', b'App'), (b'lesson-plan', b'Lesson plan'), (b'story', b'Story'), (b'software', b'Software')], max_length=100),
        ),
    ]
