# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-08 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bona_fides', '0006_auto_20170908_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='url',
            field=models.CharField(blank=True, max_length=1000, unique=True),
        ),
    ]
