# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-09 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bona_fides', '0007_auto_20170908_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text=b'The title of the talk', max_length=1000)),
                ('venue', models.CharField(help_text=b'The host of the talk', max_length=1000)),
                ('location', models.CharField(help_text=b'The location of the venue', max_length=1000)),
                ('date', models.DateField(help_text=b'The date of the talk')),
                ('video_url', models.CharField(max_length=1000, unique=True)),
                ('slides_url', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.AlterField(
            model_name='clip',
            name='url',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
