# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-09 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bona_fides', '0008_auto_20170909_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='video_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
