# Generated by Django 4.0.2 on 2022-06-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bona_fides", "0012_doc_alter_award_id_alter_clip_id_alter_skill_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="award",
            options={"ordering": ("-year", "title")},
        ),
        migrations.AddField(
            model_name="award",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
