# Generated by Django 6.0.1 on 2026-01-10 05:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bona_fides", "0013_alter_award_options_award_year"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="socialmediaprofile",
            options={"ordering": ("title",)},
        ),
    ]
