# Generated by Django 6.0.1 on 2026-01-11 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bona_fides", "0014_alter_socialmediaprofile_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SocialMediaProfile",
        ),
    ]
