# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-28 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coltrane', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopDomain',
        ),
        migrations.DeleteModel(
            name='TopTag',
        ),
    ]
