# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-29 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coltrane', '0003_auto_20170605_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='repr_image',
            field=models.CharField(blank=True, default=b'', max_length=1000),
        ),
    ]
