# Generated by Django 5.2.17 on 2026-08-23 16:40

from django.db import migrations

LEGACY_MODEL_NAMES = [
    "beer",
    "book",
    "commit",
    "link",
    "location",
    "movie",
    "photo",
    "shout",
    "ticker",
    "track",
]


def delete_legacy_content_types(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    ContentType.objects.filter(app_label="coltrane", model__in=LEGACY_MODEL_NAMES).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("coltrane", "0007_remove_slogan_state"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Beer",
        ),
        migrations.DeleteModel(
            name="Book",
        ),
        migrations.DeleteModel(
            name="Commit",
        ),
        migrations.DeleteModel(
            name="Link",
        ),
        migrations.DeleteModel(
            name="Location",
        ),
        migrations.DeleteModel(
            name="Movie",
        ),
        migrations.DeleteModel(
            name="Photo",
        ),
        migrations.DeleteModel(
            name="Shout",
        ),
        migrations.RemoveField(
            model_name="ticker",
            name="content_type",
        ),
        migrations.DeleteModel(
            name="Track",
        ),
        migrations.DeleteModel(
            name="Ticker",
        ),
        migrations.RunPython(delete_legacy_content_types, migrations.RunPython.noop),
    ]
